apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/managed-by: kustomize
  name: argocd-image-updater-github
  namespace: argocd
spec:
  pullRequest:
    github:
      # The GitHub organization or user.
      owner: myorg
      # The Github repository
      repo: myrepository
      # For GitHub Enterprise (optional)
      api: https://git.example.com/
      # Reference to a Secret containing an access token. (optional)
      tokenRef:
        secretName: github-token
        key: token
  applicationRefs:
    - namePattern: "app-001"
      images:
        - alias: "nginx"
          imageName: "nginx:1.17.10"
      writeBackConfig:
        method: "git:secret:argocd-image-updater/git-creds"
        gitConfig: # Group git-related settings. Should be ignored when writeBackMethod: "argocd"
          repository: "git@github.com:example/example.git"
          branch: "main"
          writeBackTarget: "helmvalues:/helm/config/test-values.yaml" # OR "kustomization:/config/overlays/bar" OR "helmvalues:/{{ .app.path.path }}/values.yaml" - for ApplicationSet.
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/managed-by: kustomize
  name: argocd-image-updater-gitlab
  namespace: argocd
spec:
  writeBackConfig:
    method: "git:secret:argocd-image-updater/git-creds"
  pullRequest:
    gitlab:
      # The GitLab project ID.
      project: "12341234"
      # For self-hosted GitLab (optional)
      api: https://git.example.com/
      # Reference to a Secret containing an access token. (optional)
      tokenRef:
        secretName: gitlab-token
        key: token
      # If true, skips validating the SCM provider's TLS certificate - useful for self-signed certificates.
      insecure: false
  applicationRefs:
    - namePattern: "app-001"
      images:
        - alias: "nginx"
          imageName: "nginx:1.17.10"